name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual runs
    inputs:
      verbose:
        description: 'Enable verbose test output'
        required: false
        default: false
        type: boolean
      show-console-logs:
        description: 'Show console.log/error output from tests'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Type check
        run: npm run typecheck

      - name: Run tests
        run: npm test -- --silent
        env:
          CI: true
          FORCE_COLOR: 0

      - name: Generate coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '20.x'
        run: npm run test:coverage

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '20.x'
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          flags: unittests
          fail_ci_if_error: false
